### ISSUE TITLE
Claim complete flag handling

### ISSUE THREAD

**Issue by akru** [staketechnologies/lockdrop-ui#127]
## Description

Lockdrop UI ignore `claim.complete` field and propose user to request a claim again.

![image](https://user-images.githubusercontent.com/786394/92301145-b8d82900-ef69-11ea-8948-bab4051f3467.png)

## Fix

Check `complete` flag and don't do anything if claim finish.

**Comment by hoonsubin** [comment]
this part should have handled that https://github.com/staketechnologies/lockdrop-ui/blob/master/src/components/ClaimStatus.tsx#L650
Might be issue with updating claim state

**Comment by akru** [comment]
Just an optimization, when claim complete we shouldn't handle it at all.
