### ISSUE TITLE
Locked Token Not Founded

### ISSUE THREAD

**Issue by SotaWatanabe** [staketechnologies/lockdrop-ui#136]
**Describe the bug**
A community member locked ETH but the locked ETH isn't reflected on the page like below
 
<img width="1282" alt="Screen Shot 2020-09-07 at 18 49 46" src="https://user-images.githubusercontent.com/29359048/92374725-18d1f980-f13b-11ea-817c-2cf83748dc5a.png">

**To Reproduce**
1. Go to 'The lockdrop page'
2. Click on 'Unlock token''
3. See error

**Desktop (please complete the following information):**

**Comment by SotaWatanabe** [comment]
How to check this number?

**Comment by hoonsubin** [comment]
look at the global lock list tab. It shows the total lock number
![bandicam 2020-09-07 19-05-09-564](https://user-images.githubusercontent.com/40356749/92376138-140e4500-f13d-11ea-91a8-8f491c9cd356.jpg)
If this is 1000 or less than 2,500, it means it's not fully loaded

**Comment by rthamata80** [comment]
seems mine is different issue.
let me recap my issue.  I tried lockdrop for 2 ETH for 1000 days(second transaction from same wallet, earlier one went fine) , ETH deducted from wallet but recieved "Invalid Character
![lockdrop page error](https://user-images.githubusercontent.com/36288528/92396560-33808000-f0f3-11ea-8ca2-c30c6f4208a6.jpg)
![Lockdrop_locked ETH](https://user-images.githubusercontent.com/36288528/92396561-34191680-f0f3-11ea-89c7-21b9d5f2a298.jpg)

"  
now when i'm trying to get into lockdrop page again , (both Chrome and Firefox) i'm getting red popup with error message

**Comment by XperezMa** [comment]
> 
> 
> **Describe the bug**
> A community member locked ETH but the locked ETH isn't reflected on the page like below
> 
> <img alt="Screen Shot 2020-09-07 at 18 49 46" width="1282" src="https://user-images.githubusercontent.com/29359048/92374725-18d1f980-f13b-11ea-817c-2cf83748dc5a.png">
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to 'The lockdrop page'
> 
>     2. Click on 'Unlock token''
> 
>     3. See error
> 
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. iOS]
> 
>     * Browser [e.g. chrome, safari]
> 
>     * Version [e.g. 22]

I had the same problem yesterday. I go to my lock-drop but the webpage says I do not have eth blocked but I do. I refresh the web, delete cookies and cache but the problem is still there. So I do not know if I still having my eth blocked and when it will unblocked, because the countdown disappears.
