### ISSUE TITLE
Error while connecting with metamask.

### ISSUE THREAD

**Issue by Revac** [staketechnologies/lockdrop-ui#137]
Hi,

When lockdrop site try syncing with ethereum network error like below pop up.
The entire page turns white and empty.

![image](https://user-images.githubusercontent.com/5278463/92377707-dab9e300-f104-11ea-85d8-b300fa76680b.png)

**Comment by hoonsubin** [comment]
@Revac thank you for submitting this issue. This bug is known to occur due to improper caching data being loaded. This is usually solved by clearing your browser history and local storage. If the problem persists, please reply to this comment. If it is solved, please close this issue

**Comment by SotaWatanabe** [comment]
I got the same issue today.  After clearing the browser's data, it works good.
