### ISSUE TITLE
Can not read 1st Lockdorp

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#138]
![photo_2020-09-08 12 46 00](https://user-images.githubusercontent.com/6259384/92430973-45d0eb80-f1d1-11ea-8acd-ee313475fa7d.jpeg)

> Chrome からFirst lock dropにアクセスしようとしたところ、このような表示が現れページが進みません。
> ディスコードの方でも似たような議論があったようなのでブラウザの履歴やキャッシュをクリアしてみましたが改善しないため、こちらにてご報告いたします。

When I try to access the First lock drop from Chrome, the above message appears and the page does not proceed.
There seems to be a similar discussion in Discord, so I tried clearing the history and cache of the browser, but since it does not improve, I will report here.

**Comment by SotaWatanabe** [comment]
What are the problem and any solutions?

**Comment by hoonsubin** [comment]
changed number to string method.
the `.toString()` method was automatically formatting the string that cannot be read by BigNumber, so I changed to `.toFixed()` method which fixes it.
