### ISSUE TITLE
0x6a80 invalid data received error from Ledger device with MetaMask

### ISSUE THREAD

**Issue by hoonsubin** [staketechnologies/lockdrop-ui#144]
**Describe the bug**
Several users have reported that signing a lock transaction with Ledger from MetaMask gives them the `TransportStatusError. Ledger device: Invalid data received (0x6a80)` error and the transaction fails.

**To Reproduce**
1. Open the Ethereum lockdrop page
2. input data (duration, amount, introducer, etc.)
3. Submit transaction

**Expected behavior**
The user should be able to sign the transaction from their ledger device without any issue.

**Screenshots**

![IMG_0508](https://user-images.githubusercontent.com/40356749/93584328-1e073200-f9e0-11ea-9a22-4369cb9e6be5.JPG)

**Desktop (please complete the following information):**
 - OS: Windows, MacOS
 - Browser Chrome

**Additional context**
Considering that some users were able to lock their token with Ledger without any problem, this may be due to compatibility issues with either the browser, MM extension, or Ledger firmware.
This error requires more samples before persuing further investigation.

**Comment by hoonsubin** [comment]
issue can be solved by enabling contract data from Ledger

**Comment by besiwims** [comment]
TransportStatusError. Ledger device: Invalid data received

How do I enable contract data from ledger

**Comment by padalan** [comment]
Ethereum app --> Settings --> Enable
