### ISSUE TITLE
Oracle doesn't work correctly

### ISSUE THREAD

**Issue by SotaWatanabe** [staketechnologies/lockdrop-ui#146]
Some oracles don't work correctly and can't claim PLM

<img width="643" alt="Screen Shot 2020-09-23 at 10 32 38" src="https://user-images.githubusercontent.com/29359048/93954266-426c6100-fd88-11ea-8f92-be38e2bd82b7.png">

**Comment by lukasyanseu** [comment]
any update?

**Comment by hoonsubin** [comment]
@lukasyanseu sorry for the late replay. Yes, we were aware of this issue a few days ago, and now we are working on a fix for it. This is done by adding a timestamp to the unclaimed real-time lockdrop request events, cache them to a backend server to reduce the UI's workload, and modify the lockdrop page to use this information to see if a certain claim request has been hanging for more than 30 minutes, and send another request if it's true.

And yes, just to fix this error, I am literally working on both the UI page and the server application.

- UI patch draft: https://github.com/staketechnologies/lockdrop-ui/pull/147
- Server patch draft: https://github.com/hoonsubin/lockdrop-api-server/pull/5

**Comment by lukasyanseu** [comment]
> @lukasyanseu sorry for the late replay. Yes, we were aware of this issue a few days ago, and now we are working on a fix for it. This is done by adding a timestamp to the unclaimed real-time lockdrop request events, cache them to a backend server to reduce the UI's workload, and modify the lockdrop page to use this information to see if a certain claim request has been hanging for more than 30 minutes, and send another request if it's true.
> 
> And yes, just to fix this error, I am literally working on both the UI page and the server application at the same time.
> 
> * UI patch draft: #147
> * Server patch draft: [hoonsubin/lockdrop-api-server#5](https://github.com/hoonsubin/lockdrop-api-server/pull/5)


Thank you for explaining. Does it mean that I do not need to do anything , just wait for claim re-try after your fix?

**Comment by hoonsubin** [comment]
@lukasyanseu that is correct. After when this patch is live, you just have to access the lockdrop page, and it will try to send another request for failing ones

**Comment by hoonsubin** [comment]
@lukasyanseu sorry for the late response. The issue should have been fixed now. Please check your lockdrop page
