### ISSUE TITLE
Having Issues with the lockdrop

### ISSUE THREAD

**Issue by Samali1222** [staketechnologies/lockdrop-ui#148]
Hey there 
can you guys plz help me out with the Claimed Lockdrop was  Declines and i cant claim my PLD.And my ETH is still lock im going to attach Picture to see if that could help me show you what im talking about 
![Pla](https://user-images.githubusercontent.com/67750171/94300945-9446ef80-ff1e-11ea-81c0-5d3fe6014ebd.JPG)

**Comment by hoonsubin** [comment]
@Samali1222 can you paste the claim ID here? I'll look into it and get back to you later

@akru I think this is the first time seeing the validator nodes disagreeing with a claim request, what do you think the cause is?

**Comment by Samali1222** [comment]
Hey Akru

Claim ID: 0x4909560780d20315c688dbcdcb97dbaafa767d559407ded48fb30297f9c19e1c

im not to sure i was just waiting for the
Approvals but i tried a different lockdrop with the same wallet
0x9e0efd35c3aea7a90ad4ae2447eee717264f114946459568917321143d9537e3
and everything worked out fine im not to sure whats going on
Thank you
Sam

**Comment by akru** [comment]
@hoonsubin i guess the request was send on edge of confirmation limit.

@Samali1222 could you request confirmation again please.

**Comment by Samali1222** [comment]
Hey there I tried but it dosent allow me to do so

**Comment by kyoungrok0517** [comment]
The same situation here. I don't like this kind of glitches :) The UI should give me the option to recover if something went wrong.

**Comment by hoonsubin** [comment]
@kyoungrok0517 @Samali1222  allowing the users to resubmit a hanging claim request can open up to RPC ban (this is the case when sending too much unsigned data from lkadot.js.org/apps/ as well), and that is really hard to fix. So the safest way is to create a server to track all unfinished claim requests and resubmit them at a certain interval. This way, the client can stay the same.

**Comment by kyoungrok0517** [comment]
> @kyoungrok0517 @Samali1222  allowing the users to resubmit a hanging claim request can open up to RPC ban (this is the case when sending too much unsigned data from polkadot.js.org/apps/ as well), and that is really hard to fix. So the safest way is to create a server to track all unfinished claim requests and resubmit them at a certain interval. This way, the client can stay the same.

Thanks for the reply. But as a user what I want is the necessary action done at server side so that the clients don't have to care about exceptional cases like this. Whatever the reason is, the system locked my ethers but I couldn't get the PLMs that should have been sent to my wallet. I want the situation be fixed. Nothing more.

**Comment by kyoungrok0517** [comment]
claim ID: 0x6ed8b3f5dc1abed21b28f66f2c30004f6613759c2aa343570a482fb587bd0352

**Comment by hoonsubin** [comment]
@Samali1222 according to the data, it seems like you have already claimed your tokens for 0x4909560780d20315c688dbcdcb97dbaafa767d559407ded48fb30297f9c19e1c

**Comment by Samali1222** [comment]
@hoonKim cant seem to see my plm  in my wallet before I used to see a
refresh icon in the right side of the screen for that lockdrop I did can
you help me find my tokens plz

**Comment by hoonsubin** [comment]
@Samali1222 usually the rewards are sent to your default Plasm net address, or the address that you specified. To help resolve your confusion, I'll add a lockdrop dashboard that tracks where all tokens are sent.

**Comment by SotaWatanabe** [comment]
Some users can't get enough upvotes. then, they can't claim/
<img width="504" alt="Screen Shot 2020-09-28 at 11 36 29" src="https://user-images.githubusercontent.com/29359048/94385069-1d5c6180-017f-11eb-90d3-f85da10cc1d3.png">

**Comment by vshengwu** [comment]
Claim ID: 0x45ced5aa8ee88a4c2737b2ebb45d4f71ac867a344a33c15a79876cb7fbb2cd49
can anybody help me why the confirm is 4 stay for about 20 hours long time，thanks。
<img width="1199" alt="WX20200928-154421@2x" src="https://user-images.githubusercontent.com/72007947/94404613-e0559680-01a1-11eb-88f1-d7f3649f95f0.png">

**Comment by icetii** [comment]
Hello can you help me!
I see 6 Claim Declines, why and what i need doing?
<img width="685" alt="fdsagadfgfdg" src="https://user-images.githubusercontent.com/72021072/94429780-89e55980-019b-11eb-8894-4f91e369e280.png">

**Comment by Samali1222** [comment]
@hoon kim i tried looking for the tokens in my wallet but nothing yet But
question im still show more Declines then Approvals

**Comment by tradeire** [comment]
![image](https://user-images.githubusercontent.com/72049781/94491335-f08c6680-01df-11eb-95fa-8f4a283c892f.png)
Claim ID: 0x3afde695b598a867592d09094bdc709921a9d80fca1962053cf272769129ec5e

I am having similar problem :-/

**Comment by Samali1222** [comment]
@ hoon Kim
do you have an updated on the issues?
