### ISSUE TITLE
Lockdrop Issue - Unable to see PLM to claim

### ISSUE THREAD

**Issue by CaptainStake** [staketechnologies/lockdrop-ui#151]
**Describe the bug**
Ethereum lockdrop worked and I can see my locks & the transaction hash has 84 confirmations
https://etherscan.io/tx/0x1c973fde5c4bc278f0ce6d78e3eaf4eacf4d8ce6b992ede86d7c35950e960aa5
The option to claim PLM is not appearing
There is a mix of "unexpected end of JSON input" & "Failed to Fetch"

**To Reproduce**
I don't know if you can I am using Chrome I am logged into both my Meta Mask & Polka WEB 3.0  extensions

**Expected behavior**
I expected to be able to claim my PLM 

**Screenshots**
![image](https://user-images.githubusercontent.com/72110719/94626388-ebe4b280-02b2-11eb-85b5-de6a5c987e21.png)
![image](https://user-images.githubusercontent.com/72110719/94626527-2a7a6d00-02b3-11eb-8fdd-756abec170c9.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 85.0.4183.121 (Official Build) (64-bit)
 - 

**Additional context**

**Comment by CaptainStake** [comment]
![image](https://user-images.githubusercontent.com/72110719/94627404-572f8400-02b5-11eb-8b50-a595e9b91c2f.png)
Also getting this now

**Comment by hoonsubin** [comment]
This should be fixed with the latest update
