### ISSUE TITLE
Total Locked Value and Global Locks value are different.

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#21]
Maybe, there should be equal.
![image](https://user-images.githubusercontent.com/6259384/79182466-d76a4600-7e49-11ea-8271-9299cd31ccdf.png)

**Comment by hoonsubin** [comment]
Fixed, please check and close this issue for me

**Comment by akru** [comment]
The same problem on https://plasmnet.io page

**Comment by hoonsubin** [comment]
@akru I've found that the issue stems from these functions
https://github.com/staketechnologies/lockdrop-ui/blob/master/app/src/helpers/lockdrop/EthereumLockdrop.ts#L21
https://github.com/staketechnologies/plasmnet.io/blob/master/src/components/LockdropPanel.tsx#L161
So far I was not able to determine why the values are different or how to fix it. I'll continue my research but any help would be appreciated.

**Comment by akru** [comment]
I guess one piece of code ignore `failed` transactions but another do calculation correct.

**Comment by hoonsubin** [comment]
you were correct, etherscan api also records failed transaction as well. I'll fix it

**Comment by hoonsubin** [comment]
@satellitex @akru fixed the glitch for both pages
https://github.com/staketechnologies/plasmnet.io/commit/c40e26f539347f1bd8f1e8b23f0d986e3cb4ac45

**Comment by satellitex** [comment]
@hoonsubin 
This does not exist in this case, but the total amount may change if you send money directly to the contract address.
Nobody can get a case like this, so it may be an imaginary fear.

**Comment by hoonsubin** [comment]
> @hoonsubin
> This does not exist in this case, but the total amount may change if you send money directly to the contract address.
> Nobody can get a case like this, so it may be an imaginary fear.

I don’t think that will happen with this page because I made it so that the value is counted via the emitted Lock Event and not the value inside the contract. Having said this, your theory does apply to plasmnet.io because that is counted via contract transactions in etherscan. I see if I can do anything about it

**Comment by satellitex** [comment]
@hoonsubin Ok. That's goods.
