### ISSUE TITLE
Add PR CI

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#22]
It would be better to rotate the CI for each PR. You can prevent errors in the master branch. Please refer to the following.

https://github.com/staketechnologies/plasmnet.io/blob/master/.github/workflows/pr-any.yml

**Comment by hoonsubin** [comment]
I think I did it correctly, please it for me and tell me if there's anything wrong

**Comment by satellitex** [comment]
https://github.com/staketechnologies/lockdrop-ui/pull/23
