### ISSUE TITLE
Create 2nd Lockdrop landing page

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#28]
## Required Tasks
- [x] create a landing page that will allow users to access every lockdrop related pages

## Estimated dev time
around 2 working days

**Comment by satellitex** [comment]
~ Wed or Thursday.

**Comment by hoonsubin** [comment]
Sneak peek of what I'm making so far
![IMG_0348](https://user-images.githubusercontent.com/40356749/82226049-f421fe00-9960-11ea-8126-c5774a9db92a.png)
