### ISSUE TITLE
1 page please

### ISSUE THREAD

**Issue by SotaWatanabe** [staketechnologies/lockdrop-ui#3]
Currently, these are 2 lockdrop pages. Can we make it 1 page?

**Comment by hoonsubin** [comment]
can you elaborate more? The actual input form is a single-page site. The landing page is just there to choose different tokens to lock. So, in theory, we can just give the [domain]/eth-lockdrop url to the participants.
Unless if your request is to remove the landing page as a whole, in which case I can do that

**Comment by SotaWatanabe** [comment]
I mean we have 2 pages as I have attached below.

<img width="1440" alt="Screen Shot 2020-02-04 at 15 36 33" src="https://user-images.githubusercontent.com/29359048/73719959-35045700-4764-11ea-8816-49d9a1bbc879.png">
<img width="1440" alt="Screen Shot 2020-02-04 at 15 36 38" src="https://user-images.githubusercontent.com/29359048/73719964-3897de00-4764-11ea-887f-6fce58c86447.png">

I think a single page is better. What do you think?

**Comment by hoonsubin** [comment]
Yes, my point was that the first page is just the landing page when we do our lockdrop with multiple tokens (just to future proof it). You can just send the url of the second page to the participants without any issue, making it effectively a single-page app. At least that is what I think.

**Comment by hoonsubin** [comment]
@SotaWatanabe addressed in the newest PR!
