### ISSUE TITLE
Fix eth pubkey to plasm address mismatch bug

### ISSUE THREAD

**Issue by hoonsubin** [staketechnologies/lockdrop-ui#33]
## Required Tasks
- [ ] add encryption unit tests
- [ ] add unit testing for efficient work
- [ ] find the reason as to why this bug is happening!

## Description
There is a glitch where the plasm address generated from the lockdrop participant's public key does not match the one on Plasm chain. This glitch is most likely caused due to a minor issue within the cryptographic pipeline.

## Estimated dev time
two research days and 6 hours of work

**Comment by satellitex** [comment]
Checked 👍
