### ISSUE TITLE
Add token icon.

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#4]
- [x] If we select ETH, we can see the ETH icon. like below.
https://twitter.com/SwingbyProtocol/status/1217130875730702337?s=20

**Comment by hoonsubin** [comment]
Wow! I was actually thinking the exact thing! Planning on adding it (plus token specific color themes for each page as well) after I fix the contract parsing error. Or I can do it before that

**Comment by hoonsubin** [comment]
Added token icons here (WIP)
https://github.com/staketechnologies/lockdrop-ui/commit/f5eda3a5f1eb8f1b5fe4e08722953a77620f8393
