### ISSUE TITLE
View Ethereum public key.

### ISSUE THREAD

**Issue by satellitex** [staketechnologies/lockdrop-ui#41]
## Required Tasks
- [x] When click claim Plasm address, view plasm address with ethereum public key(options).

## Description
The Ethereum public key is currently not visible in the UI. Can you change it to show this?
If you’re reluctant to ask the user to provide the Ethereum public key

It's needed for sending referral bonuses.

## Estimated dev time
5/20

**Comment by hoonsubin** [comment]
finished in https://github.com/staketechnologies/lockdrop-ui/pull/42
